# Generated by Django 5.0.3 on 2024-04-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_article',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='blog_article',
            old_name='tag',
            new_name='tags',
        ),
    ]
